# 
name: imooc-nestjs
version: '3.1'
services:
  db:
    image: mysql
    restart: always
    container_name: imooc-nestjs-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      # MYSQL_USER: root
      # MYSQL_PASSWORD: root
    
    ports:
      - 3308:3306

  adminer:
    image: adminer
    container_name: imooc-nestjs-adminer
    restart: always
    ports:
      - 8082:8080

  # redis:
  #   image: redis
  #   container_name: water-nestjs-redis
  #   restart: always
  #   ports:
  #     - 6379:6379

  # redisinsight:
  #   image: redis/redisinsight:latest
  #   container_name: water-nestjs-redisinsight
  #   ports:
  #     - 5540:5540
  #   depends_on:
  #     - redis